version: '3.7'

services:
  pbs:
    build:
      context: .
      dockerfile: ./TestPbs.Dockerfile
    container_name: pbs
    hostname: pbs
    environment:
      - PBS_START_MOM=1
    ports:
      - "2222:22"
    networks:
    - default
    tty: true
    command: bash
