package provider

// Centralized descriptions for reuse across resources and data sources.
// Prefer MarkdownDescription in schemas so tfplugindocs renders them.

// Hook docs.
const (
	DescHookID         = "The unique identifier for this hook. This is the same as the name."
	DescHookAlarm      = "Specifies the number of seconds to allow a hook to run before the hook times out."
	DescHookDebug      = "debugging files under PBS_HOME/server_priv/hooks/tmp or PBS_HOME/mom_priv/hooks/tmp.  Files are named hook_<hook event>_<hook name>_<unique ID>.in, .data, and .out"
	DescHookEnabled    = "Determines whether or not a hook is run when its triggering event occurs."
	DescHookEvent      = "List of events that trigger the hook. The provision event cannot be combined with any other events."
	DescHookFailAction = "Specifies the action to be taken when hook fails due to alarm call or unhandled exception, or to an internal error such as not enough disk space or memory. Can also specify a subsequent action to be taken when hook runs successfully. Value can be either `none` or one or more of `offline_vnodes`, `clear_vnodes_upon_recovery`, and `scheduler_restart_cycle`. If this attribute is set to multiple values, scheduler restart happens last."
	DescHookFreq       = "Number of seconds between `periodic` or `exechost_periodic` triggers."
	DescHookName       = "The unique name of the hook on the server"
	DescHookOrder      = "Indicates relative order of hook execution, for hooks of the same type sharing a trigger. Hooks with lower order values execute before those with higher values. Does not apply to periodic or exechost_periodic hooks."
	DescHookType       = "The type of the hook. Cannot be set for a built-in hook."
	DescHookUser       = "Specifies who executes the hook."
)

// Node docs.
const (
	DescNodeID                 = "The unique identifier for this node. This is the same as the name."
	DescNodeComment            = "Information about this vnode. This attribute may be set by the manager to any string to inform users of any information relating to the node. If this attribute is not explicitly set, the PBS server will use the attribute to pass information about the node status, specifically why the node is down. If the attribute is explicitly set by the manager, it will not be modified by the server."
	DescNodeCurrentAoe         = "The AOE currently instantiated on this vnode. Case-sensitive. Cannot be set on server's host."
	DescNodeCurrentEoe         = "Current value of eoe on this vnode. We do not recommend setting this attribute manually."
	DescNodeInMultiNodeHost    = "Specifies whether a vnode is part of a multi-vnoded host. Used internally. Do not set."
	DescNodeMom                = "Hostname where server queries for MoM host. By default the server queries the canonicalized name of the MoM host, unless you set this attribute when you create the vnode. Can be explicitly set by Manager only via qmgr, and only at vnode creation. The server can set this to the FQDN of the host on which MoM runs, if the vnode name is the same as the hostname."
	DescNodeName               = "The name of this vnode. Must be resolvable to an IP address. Must be unique within the server."
	DescNodeNoMultinodeJobs    = "Controls whether jobs which request more than one chunk are allowed to execute on this vnode. Used for cycle harvesting."
	DescNodePartition          = "Name of partition to which this vnode is assigned. A vnode can be assigned to at most one partition."
	DescNodePNames             = "The list of resources being used for placement sets. Not used for scheduling; advisory only."
	DescNodePort               = "Port number on which MoM daemon listens. Can be explicitly set only via qmgr, and only at vnode creation."
	DescNodePoweroffEligible   = "Enables powering this vnode up and down by PBS."
	DescNodePowerProvisioning  = "Specifies whether this node is eligible to have its power managed by PBS, including whether it can use power profiles."
	DescNodePriority           = "The priority of this vnode compared with other vnodes."
	DescNodeProvisionEnable    = "Controls whether this vnode can be provisioned. Cannot be set on server's host."
	DescNodeQueue              = "Deprecated. The queue with which this vnode is associated. Each vnode can be associated with at most 1 queue. Queues can be associated with multiple vnodes. Any jobs in a queue that has associated vnodes can run only on those vnodes. If a vnode has an associated queue, only jobs in that queue can run on that vnode."
	DescNodeResourcesAvailable = "The list of resources and the amounts available on this vnode. If not explicitly set, the amount shown is that reported by the pbs_mom running on this vnode. If a resource value is explicitly set, that value is retained across restarts."
	DescNodeResvEnable         = "Controls whether the vnode can be used for advance and standing reservations. Reservations are incompatible with cycle harvesting."
)

// PBS Resource docs.
const (
	DescPbsResourceID   = "The unique identifier for this resource. This is the same as the name."
	DescPbsResourceName = "The unique name of the resource on the server"
	DescPbsResourceType = "What data type the resource takes, this can be one of boolean, string, long, size, float, string_array"
	DescPbsResourceFlag = "One of the flags specifying where the resource is defined (f, fh, nh, q, m) and the ones defining it's visibility (i, r)"
)

// Queue docs.
const (
	DescQueueID                     = "The unique identifier for this queue. This is the same as the name."
	DescQueueAclGroupEnable         = "Controls whether group access to the queue obeys the access control list defined in the acl_groups queue attribute."
	DescQueueAclGroups              = "List of groups which are allowed or denied access to this queue. The groups in the list are groups on the server host, not submitting hosts. List is evaluated left-to-right; first match in list is used."
	DescQueueAclGroupsNormalized    = "The normalized (sorted) version of acl_groups as stored by PBS."
	DescQueueAclHostEnable          = "Controls whether host access to the queue obeys the access control list defined in the acl_hosts queue attribute."
	DescQueueAclHosts               = "List of hosts from which jobs may be submitted to this queue. List is evaluated left-to-right; first match in list is used."
	DescQueueAclHostsNormalized     = "The normalized (sorted) version of acl_hosts as stored by PBS."
	DescQueueAclUserEnable          = "Controls whether user access to the queue obeys the access control list defined in the acl_users queue attribute"
	DescQueueAclUsers               = "List of users allowed or denied access to this queue. List is evaluated left-to-right; first match in list is used."
	DescQueueAclUsersNormalized     = "The normalized (sorted) version of acl_users as stored by PBS."
	DescQueueAltRouter              = "Deprecated. No longer used."
	DescQueueBackfillDepth          = "Specifies backfilling behavior for this queue. Sets the number of jobs that are to be backfilled around in this queue. Overrides backfill_depth server attribute. Recommendation: set this to less than 100."
	DescQueueCheckpointMin          = "Minimum number of minutes of CPU time or walltime allowed between checkpoints of a job. If a user specifies a time less than this value, this value is used instead. The value given in checkpoint_min is used for both CPU minutes and walltime minutes."
	DescQueueDefaultChunk           = "The list of resources which will be inserted into each chunk of a job's select specification if the corresponding resource is not specified by the user. This provides a means for a site to be sure a given resource is properly accounted for even if not specified by the user."
	DescQueueEnabled                = "Specifies whether this queue accepts new jobs."
	DescQueueFromRouteOnly          = "Specifies whether this queue accepts jobs only from routing queues, or from both execution and routing queues."
	DescQueueKillDelay              = "The time delay (seconds) between sending SIGTERM and SIGKILL when a `qdel` command is issued against a running job. Default value is 10 seconds."
	DescQueueMaxArraySize           = "The maximum number of subjobs that are allowed in an array job."
	DescQueueMaxGroupRes            = "Limit attribute. The maximum amount of the specified resource that any single group may consume."
	DescQueueMaxGroupResSoft        = "Limit attribute. The soft limit on the amount of the specified resource that any single group may consume. If a group is consuming more than this amount of the specified resource, their jobs are eligible to be preempted by jobs from groups who are not over their soft limit."
	DescQueueMaxGroupRun            = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by users in a single group that are allowed to be running from this queue at one time."
	DescQueueMaxGroupRunSoft        = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by users in a single group that are allowed to be running from this queue at one time. If a group has more than this number of jobs running, their jobs are eligible to be preempted by jobs from groups who are not over their soft limit."
	DescQueueMaxQueuable            = " Old limit attribute.  Incompatible with new limit attributes.  The maximum number of jobs allowed to reside in this queue at any given time."
	DescQueueMaxQueued              = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs allowed to reside in this queue at any given time."
	DescQueueMaxQueuedRes           = "Limit attribute. The maximum number of jobs allowed to be queued in or running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRes                 = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs queued in or running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRun                 = "Limit attribute. The maximum number of jobs allowed to be running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRunRes              = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRunResSoft          = "Limit attribute. Soft limit on the amount of the specified resource allowed to be allocated to jobs running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRunSoft             = "Limit attribute. Soft limit on the number of jobs allowed to be running from this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueMaxRunning             = "Old limit attribute. Incompatible with new limit attributes. For an execution queue, this is the largest number of jobs allowed to be running at any given time. For a routing queue, this is the largest number of jobs allowed to be transiting from this queue at any given time."
	DescQueueMaxUserRes             = "Old limit attribute. Incompatible with new limit attributes. The maximum amount of the specified resource that any single user may consume."
	DescQueueMaxUserResSoft         = "Old limit attribute. Incompatible with new limit attributes. The soft limit on the amount of the specified resource that any single user may consume. If a user is consuming more than this amount of the specified resource, their jobs are eligible to be preempted by jobs from users who are not over their soft limit."
	DescQueueMaxUserRun             = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by a single user that are allowed to be running from this queue at one time."
	DescQueueMaxUserRunSoft         = "Old limit attribute. Incompatible with new limit attributes. The soft limit on the number of jobs owned by any single user that are allowed to be running from this queue at one time. If a user has more than this number of jobs running, their jobs are eligible to be preempted by jobs from users who are not over their soft limit."
	DescQueueName                   = "The unique name of the queue on the server"
	DescQueueNodeGroupKey           = "Specifies the resources to use for placement sets (node grouping). Overrides server's node_group_key attribute. Specified resources must be of type string_array."
	DescQueuePartition              = "Name of partition to which this queue is assigned. Cannot be set for routing queue. An execution queue cannot be changed to a routing queue while this attribute is set."
	DescQueuePriority               = "The priority of this queue compared to other queues of the same type in this PBS complex. Priority can define a queue as an express queue. See preempt_queue_prio in Chapter 4"
	DescQueueQueuedJobsThreshold    = "Limit attribute.  The maximum amount of the specified resource allowed to be allocated to jobs queued in this queue.  Can be specified for  projects, users, groups, or all.  Cannot be used with old limit attributes."
	DescQueueQueuedJobsThresholdRes = "Limit attribute.  The maximum amount of the specified resource allowed to be allocated to jobs queued in this queue.  Can be specified for  projects, users, groups, or all.  Cannot be used with old limit attributes."
	DescQueueQueuedRes              = "Limit attribute. The maximum number of jobs allowed to be queued in this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueQueuedResMax           = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs queued in this queue. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescQueueQtype                  = "The type of this queue. This attribute must be explicitly set at queue creation to one of Execution/Route"
	DescQueueResourcesAvailable     = "The list of resources and amounts available to jobs running in this queue. The sum of the resource of each type used by all jobs running from this queue cannot exceed the total amount listed here."
	DescQueueResourcesMax           = "The maximum amount of each resource that can be requested by a single job in this queue. This queue value supersedes any server wide maximum limit."
	DescQueueResourcesMin           = "The minimum amount of each resource that can be requested by a single job in this queue."
	DescQueueResourcesDefault       = "The list of default resource values which are set as limits for a job residing in this queue and for which the job did not specify a limit. If not set, the default limit for a job is determined by the first of the following attributes which is set: server's `resources_default`, queue's `resources_max`, server's `resources_max`. If none of these is set, the job gets unlimited resource usage."
	DescQueueRouteDestinations      = "The list of destinations to which jobs may be routed. Must be set to at least one valid destination."
	DescQueueRouteHeldJobs          = "Specifies whether jobs in the held state can be routed from this queue."
	DescQueueRouteLifetime          = "The maximum time a job is allowed to reside in this routing queue. If a job cannot be routed in this amount of time, the job is aborted."
	DescQueueRouteRetryTime         = "Time delay between routing retries. Typically used when the network between servers is down."
	DescQueueRouteWaitingJobs       = "Specifies whether jobs whose `Execution_Time` attribute value is in the future can be routed from this queue."
	DescQueueStarted                = "If this is an execution queue, specifies whether jobs in this queue can be scheduled for execution, or if this is a routing queue, whether jobs can be routed."
)

// Server docs.
const (
	DescServerID                            = "The unique identifier for this server. This is the same as the name."
	DescServerAclHostEnable                 = "Specifies whether the server obeys the host access control list in the acl_hosts server attribute."
	DescServerAclHostsMomsEnable            = "Specifies whether all MoMs are automatically allowed to contact the server with the same privilege as hosts listed in the acl_hosts server attribute."
	DescServerAclHosts                      = "List of hosts from which services can be requested of this server. Requests from the server host are always honored whether or not that host is in the list. This list contains the fully qualified domain names of the hosts. List is evaluated left-to-right; first match in list is used."
	DescServerAclHostsNormalized            = "The normalized (sorted) version of acl_hosts as stored by PBS."
	DescServerAclResvGroupEnable            = "Specifies whether the server obeys the group reservation access control list in the acl_resv_groups server attribute."
	DescServerAclResvGroups                 = "List of groups allowed or denied permission to create reservations in this PBS complex. The groups in the list are groups on the server host, not submission hosts. List is evaluated left-to-right; first match in list is used."
	DescServerAclResvGroupsNormalized       = "The normalized (sorted) version of acl_resv_groups as stored by PBS."
	DescServerAclResvHostEnable             = "Specifies whether the server obeys the host reservation access control list in the acl_resv_hosts server attribute."
	DescServerAclResvHosts                  = "List of hosts from which reservations can be created in this PBS complex. This list is made up of the fully-qualified domain names of the hosts. List is evaluated left-to-right; first match in list is used."
	DescServerAclResvHostsNormalized        = "The normalized (sorted) version of acl_resv_hosts as stored by PBS."
	DescServerAclResvUserEnable             = "Specifies whether the server limits which users are allowed to create reservations, according to the access control list in the acl_resv_users server attribute."
	DescServerAclResvUsers                  = "List of users allowed or denied permission to create reservations in this PBS complex. List is evaluated left-to-right; first match in list is used."
	DescServerAclResvUsersNormalized        = "The normalized (sorted) version of acl_resv_users as stored by PBS."
	DescServerAclRoots                      = "List of users with root privilege who can submit and run jobs in this PBS complex. For any job whose owner is root or Administrator, the job owner must be listed in this access control list, or the job is rejected. List is evaluated left-to-right; first match in list is used."
	DescServerAclRootsNormalized            = "The normalized (sorted) version of acl_roots as stored by PBS."
	DescServerAclUserEnable                 = "Specifies whether the server limits which users are allowed to run commands at the server, according to the control list in the acl_users server attribute."
	DescServerAclUsers                      = "List of users allowed or denied permission to run commands at this server. List is evaluated left-to-right; first match in list is used."
	DescServerAclUsersNormalized            = "The normalized (sorted) version of acl_users as stored by PBS."
	DescServerBackfillDepth                 = "Specifies backfilling behavior. Sets the number of jobs that are to be backfilled around. Overridden by backfill_depth queue attribute. Recommendation: set this to less than 100."
	DescServerComment                       = "Informational text. Can be set by a scheduler or other privileged client."
	DescServerDefaultChunk                  = "The list of resources which will be inserted into each chunk of a job's select specification if the corresponding resource is not specified by the user. This provides a means for a site to be sure a given resource is properly accounted for even if not specified by the user."
	DescServerDefaultQdelArguments          = "Argument to qdel command. Automatically added to all qdel commands. See qdel(1B). Overrides standard defaults. Overridden by arguments given on the command line."
	DescServerDefaultQsubArguments          = "Arguments that are automatically added to the qsub command. Any valid arguments to qsub command, such as job attributes. Setting a job attribute via default_qsub_arguments sets that attribute for each job which does not explicitly override it. See qsub(1B). Settable by the administrator via the qmgr command. Overrides standard defaults. Overridden by arguments given on the command line and in script directives."
	DescServerDefaultQueue                  = "The name of the default target queue. Used for requests that do not specify a queue name. Must be set to an existing queue."
	DescServerEligibleTimeEnable            = "Enables accruing job wait time in the job's eligible_time attribute."
	DescServerElimOnSubjobs                 = "Specifies whether the server max_queued limit attribute counts each array job as a single job, or counts each subjob as a single job."
	DescServerFlatuid                       = "Used for authorization allowing users to submit and alter jobs. Specifies whether user names are treated as being the same across the PBS server and all submission hosts in the PBS complex. Can be used to allow users without accounts at the server host to submit jobs. If UserA has an account at the server host, PBS requires that UserA@<server host> is the same as UserA@<execution host>."
	DescServerJobHistoryDuration            = "The length of time PBS will keep each job's history."
	DescServerJobHistoryEnable              = "Enables job history management. Setting this attribute to True enables job history management."
	DescServerJobRequeueTimeout             = "The amount of time that can be taken while requeueing a job. Minimum allowed value: 1 second. Maximum allowed value: 3 hours."
	DescServerJobSortFormula                = "Formula for computing job priorities. Described in the PBS Professional Administrator's Guide. If the attribute job_sort_formula is set, all schedulers use the formula in it to compute job priorities. When this scheduler sorts jobs according to the formula, it computes a priority for each job, where that priority is the value produced by the formula. Jobs with a higher value get higher priority."
	DescServerJobscriptMaxSize              = "Limit on the size of any job script."
	DescServerLogEvents                     = "The types of events the server logs as an integer representation of the bits"
	DescServerMailer                        = "Path to mailer to be used by PBS. This mailer should function similarly to sendmail."
	DescServerMailFrom                      = "The username from which server-generated mail is sent to users. Mail is sent to this address upon failover."
	DescServerManagers                      = "List of PBS Managers."
	DescServerMaxArraySize                  = "The maximum number of subjobs allowed in any array job."
	DescServerMaxConcurrentProvision        = "The max_concurrent_provision attribute is the number of vnodes allowed to be in the process of being provisioned. Cannot be set to zero. When unset, default value is used."
	DescServerMaxGroupRes                   = "Limit attribute. The maximum amount of the specified resource that any single group may consume in this PBS complex."
	DescServerMaxGroupResSoft               = "Limit attribute. The soft limit for the specified resource that any single group may consume in this complex. If a group is consuming more than this amount of the specified resource, their jobs are eligible to be preempted by jobs from groups who are not over their soft limit."
	DescServerMaxGroupRun                   = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by the users in one group allowed to be running within this complex at one time."
	DescServerMaxGroupRunSoft               = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by the users in one group allowed to be running in this complex at one time. If a group has more than this number of jobs running, their jobs are eligible to be preempted by jobs from groups who are not over their soft limit."
	DescServerMaxJobSequenceId              = "Maximum value of sequence number in a job ID, job array ID, or reservation ID. Minimum allowed is 9999999. Maximum allowed is 999999999999. After specified maximum for sequence number has been reached, job IDs start again at 0."
	DescServerMaxQueued                     = "Limit attribute. The maximum number of jobs allowed to be queued or running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes. The effect of this limit depends on how the elim_on_subjobs attribute is set; when elim_on_subjobs is True (the default), max_queued counts each subjob as a job; when elim_on_subjobs is False, max_queued counts each array job as a single job."
	DescServerMaxQueuedRes                  = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs queued or running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerMaxRun                        = "Limit attribute. The maximum number of jobs allowed to be running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerMaxRunRes                     = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerMaxRunResSoft                 = "Limit attribute. Soft limit on the amount of the specified resource allowed to be allocated to jobs running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerMaxRunSoft                    = "Limit attribute. Soft limit on the number of jobs allowed to be running in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerMaxRunning                    = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs in this complex allowed to be running at any given time."
	DescServerMaxUserRes                    = "Limit attribute. The maximum amount of the specified resource that any single user may consume within this complex."
	DescServerMaxUserResSoft                = "Limit attribute. The soft limit on the amount of the specified resource that any single user may consume within this complex. If a user is consuming more than this amount of the specified resource, their jobs are eligible to be preempted by jobs from users who are not over their soft limit."
	DescServerMaxUserRun                    = "Old limit attribute. Incompatible with new limit attributes. The maximum number of jobs owned by a single user allowed to be running within this complex at one time."
	DescServerMaxUserRunSoft                = "Old limit attribute. Incompatible with new limit attributes. The soft limit on the number of jobs owned by a single user that are allowed to be running within this complex at one time. If a user has more than this number of jobs running, their jobs are eligible to be preempted by jobs from users who are not over their soft limit."
	DescServerName                          = "The unique name for the PBS server"
	DescServerNodeFailRequeue               = "Controls whether running jobs are automatically requeued or are deleted when the primary execution host fails. Number of seconds to wait after losing contact with Mother Superior before requeueing or deleting jobs. Reverts to default value when server is restarted."
	DescServerNodeGroupEnable               = "Specifies whether placement sets (which includes node grouping) are enabled. See node_group_key server attribute."
	DescServerNodeGroupKey                  = "Specifies the resources to use for placement sets (node grouping). Overridden by queue's node_group_key attribute. See node_group_enable server attribute."
	DescServerOperators                     = "List of PBS Operators."
	DescServerPbsLicenseInfo                = "Location of license server(s)."
	DescServerPbsLicenseLingerTime          = "The number of seconds to keep an unused license, when the number of licenses is above the value given by pbs_license_min."
	DescServerPbsLicenseMax                 = "Maximum number of licenses to be checked out at any time, i.e maximum number of licenses to keep in the PBS local license pool. Sets a cap on the number of nodes or sockets that can be licensed at one time."
	DescServerPbsLicenseMin                 = "Minimum number of nodes or sockets to permanently keep licensed, i.e. the minimum number of licenses to keep in the PBS local license pool. This is the minimum number of licenses to keep checked out. If unset, PBS automatically sets the value to 0."
	DescServerPowerProvisioning             = "Reflects use of power profiles via PBS. Set by PBS to True when PBS_power hook is enabled."
	DescServerPythonGcCollectMinInterval    = "Specifies interval for Python garbage collection. For no garbage collection, set this to zero."
	DescServerPythonRestartMaxHooks         = "The maximum number of hooks to be serviced before the Python interpreter is restarted. If this number is exceeded, and the time limit set in python_restart_min_interval has elapsed, the Python interpreter is restarted."
	DescServerPythonRestartMaxObjects       = "The maximum number of objects to be created before the Python interpreter is restarted. If this number is exceeded, and the time limit set in python_restart_min_interval has elapsed, the Python interpreter is restarted."
	DescServerPythonRestartMinInterval      = "The minimum time interval before the Python interpreter is restarted. If this interval has elapsed, and either the maximum number of hooks to be serviced (set in python_restart_max_hooks) has been exceeded or the maximum number of objects to be created (set in python_restart_max_objects) has been exceeded, the Python interpreter is restarted."
	DescServerQueryOtherJobs                = "Controls whether unprivileged users are allowed to select or query the status of jobs owned by other users."
	DescServerQueuedJobsThreshold           = "Limit attribute. The maximum number of jobs allowed to be queued in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerQueuedJobsThresholdRes        = "Limit attribute. The maximum amount of the specified resource allowed to be allocated to jobs queued in the complex. Can be specified for projects, users, groups, or all. Cannot be used with old limit attributes."
	DescServerReserveRetryInit              = "Deprecated. The amount of time after a reservation becomes degraded that PBS waits before attempting to reconfirm the reservation. When this value is changed, only reservations that become degraded after the change use the new value. Must be greater than zero."
	DescServerReserveRetryTime              = "The amount of time after a reservation becomes degraded that PBS waits before attempting to reconfirm the reservation, as well as amount of time between attempts to reconfirm degraded reservations. When this value is changed, PBS uses the new value for any subsequent attempts. Must be greater than zero."
	DescServerResourcesAvailable            = "The list of available resources and their values defined on the server."
	DescServerResourcesDefault              = "The list of default job-wide resource values that are set as limits for jobs in this complex when a) the job does not specify a limit, and b) there is no queue default. The value for a string array, e.g. resources_default.<string array resource>, can contain only one string. For host-level resources, see the default_chunk.<resource name> server attribute."
	DescServerResourcesMax                  = "The maximum amount of each resource that can be requested by any single job in this complex, if there is not a resources_max value defined for the queue at which the job is targeted. This attribute functions as a gating value for jobs entering the PBS complex."
	DescServerRestrictResToReleaseOnSuspend = "Comma-separated list of consumable resources to be released when jobs are suspended. If unset, all consumable resources are released on suspension."
	DescServerResvEnable                    = "Specifies whether or not advance and standing reservations can be created in this complex."
	DescServerResvPostProcessingTime        = "The amount of time allowed for reservations to clean up after running jobs. Reservation duration and end time are extended by this amount of time. Jobs are not allowed to run during the cleanup period."
	DescServerRppHighwater                  = "The maximum number of messages."
	DescServerRppMaxPktCheck                = "Maximum number of TPP messages processed by the main server thread per iteration."
	DescServerRppRetry                      = "Maximum number of TPP messages processed by the main server thread per iteration."
	DescServerSchedulerIteration            = "In a fault-tolerant setup (multiple pbs_comms), when the first pbs_comm fails partway through a message, this is number of times TPP tries to use the first pbs_comm."
	DescServerSchedulingInterval            = "The time between scheduling iterations."
	DescServerWebapiAuthIssuers             = "Comma-separated list of accepted JWT token issuers. Used only when using JWT tokens generated via hpcgentoken."
	DescServerWebapiEnable                  = "Enables or disables web API support in PBS"
	DescServerWebapiOidcClientid            = "Used with external OIDC service. The client identifier generated when registering the application with the OIDC provider. For validation of OIDC ID tokens passed in http(s) requests."
	DescServerWebapiOidcProviderUrl         = "Used with external OIDC service. URL of the OIDC provider, for example https://accounts.google.com For validation of OIDC ID tokens passed in http(s) requests."
)
