name: PBS Tests

on:
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24'

jobs:
  pbs-acceptance-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Get dependencies
      run: go mod download
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Setup Test Environment
      run: |
        make test-setup
        
    - name: Run Queue Resource Tests
      env:
        TF_ACC: 1
        PBS_TEST_SERVER: localhost
        PBS_TEST_PORT: 2222
        PBS_TEST_USERNAME: root
        PBS_TEST_PASSWORD: pbs
      run: |
        make testacc
        
    - name: Collect PBS logs on failure
      if: failure()
      run: |
        cd docker_compose
        echo "=== Docker Compose Logs ==="
        docker-compose logs pbs
        echo "=== PBS Status ==="
        docker-compose exec -T pbs /opt/pbs/bin/qstat -f || true
        docker-compose exec -T pbs /opt/pbs/bin/pbsnodes -a || true
        docker-compose exec -T pbs /opt/pbs/bin/qmgr -c "list server" || true
        echo "=== Container Status ==="
        docker-compose ps
        
    - name: Cleanup test environment
      if: always()
      run: |
        make test-cleanup
